USE DATABASE SOC;
USE SCHEMA PUBLIC;

SET EXEC_ID = 12345;  -- fake ID pour pouvoir insert dans les tables

INSERT INTO R_ROOM
SELECT
    NO_CHAMBRE,
    TRIM(NOM_CHAMBRE),
    NO_ETAGE,
    TRIM(NOM_BATIMENT),
    TRIM(TYPE_CHAMBRE),
    PRIX_JOUR,
    TRY_TO_DATE(DT_CREATION),
    $EXEC_ID

FROM WRK.PUBLIC.CHAMBRE;


CREATE OR REPLACE TEMPORARY TABLE TMP_MEDC AS
SELECT DISTINCT
    TRIM(CD_MEDICAMENT)     AS MEDC_CD,
    TRIM(NOM_MEDICAMENT)    AS MEDC_NAME,
    TRIM(CONDIT_MEDICAMENT) AS MEDC_COND,
    TRIM(CATG_MEDICAMENT)   AS MEDC_CATG,
    TRIM(MARQUE_FABRI)      AS MANF_BRND
FROM WRK.PUBLIC.MEDICAMENT;


INSERT INTO R_MEDC
SELECT
    ROW_NUMBER() OVER (ORDER BY MEDC_CD, MEDC_CATG, MANF_BRND) AS MEDC_ID,
    MEDC_CD,
    MEDC_NAME,
    MEDC_COND,
    MEDC_CATG,
    MANF_BRND,
    $EXEC_ID
FROM TMP_MEDC;


INSERT INTO O_TRET
SELECT
    T.ID_TRAITEMENT,                        -- TRET_ID
    M.MEDC_ID,                              -- MEDC_ID (jointure sur 3 colonnes)
    T.QTE_MEDICAMENT,                      -- MEDC_QTY
    TRIM(T.DSC_POSOLOGIE),                 -- DOSG_DSC
    T.ID_CONSULT,                          -- CONS_ID
    T.TS_CREATION_TRAITEMENT,             -- TRET_CRTN_DTTM
    $EXEC_ID                               -- EXEC_ID
FROM WRK.PUBLIC.TRAITEMENT T
LEFT JOIN R_MEDC M
    ON TRIM(T.CD_MEDICAMENT) = M.MEDC_CD
   AND TRIM(T.CATG_MEDICAMENT) = M.MEDC_CATG
   AND TRIM(T.MARQUE_FABRI) = M.MANF_BRND;


CREATE OR REPLACE TEMPORARY TABLE TMP_PART_PERSONNEL AS
SELECT DISTINCT
    ID_PERSONNEL       AS SRC_ID,
    TRIM(FONCTION_PERSONNEL) AS SRC_TYP
FROM WRK.PUBLIC.PERSONNEL;



CREATE OR REPLACE TEMPORARY TABLE TMP_PART_PATIENT AS
SELECT DISTINCT
    ID_PATIENT AS SRC_ID,
    'Patient'  AS SRC_TYP
FROM WRK.PUBLIC.PATIENT;


CREATE OR REPLACE TEMPORARY TABLE TMP_PART_ALL AS
SELECT
    ROW_NUMBER() OVER (ORDER BY SRC_TYP, SRC_ID) AS PART_ID,
    SRC_ID,
    SRC_TYP
FROM (
    SELECT * FROM TMP_PART_PERSONNEL
    UNION
    SELECT * FROM TMP_PART_PATIENT
) AS UNIONED_PARTS;


INSERT INTO R_PART
SELECT
    PART_ID,
    SRC_ID,
    SRC_TYP,
FROM TMP_PART_ALL;
   

INSERT INTO O_TELP
SELECT
    RP.PART_ID,
    P.IND_PAYS_NUM_TELP, 
    TRIM(P.NUM_TELEPHONE),
    P.TS_CREATION_PATIENT, 
    P.TS_MAJ_PATIENT,
    $EXEC_ID
FROM WRK.PUBLIC.PATIENT P
INNER JOIN R_PART RP
    ON P.ID_PATIENT = RP.SRC_ID
   AND RP.SRC_TYP = 'Patient';


INSERT INTO O_ADDR
SELECT
    RP.PART_ID,
    TRIM(P.NUM_VOIE),
    TRIM(P.DSC_VOIE),
    TRIM(P.CMPL_VOIE),
    TRIM(P.CD_POSTAL), 
    TRIM(P.VILLE),
    TRIM(P.PAYS),
    P.TS_CREATION_PATIENT,
    P.TS_MAJ_PATIENT,
    $EXEC_ID
FROM WRK.PUBLIC.PATIENT P
INNER JOIN R_PART RP
    ON P.ID_PATIENT = RP.SRC_ID
   AND RP.SRC_TYP = 'Patient';




INSERT INTO O_INDV
SELECT
    RP.PART_ID,
    TRIM(P.NOM_PATIENT),
    TRIM(P.PRENOM_PATIENT),
    'Actif',
    P.TS_CREATION_PATIENT,
    P.TS_MAJ_PATIENT,
    P.DT_NAISS,
    TRIM(P.VILLE_NAISS),
    TRIM(P.PAYS_NAISS),
    TRIM(P.NUM_SECU),
    $EXEC_ID


FROM WRK.PUBLIC.PATIENT P
INNER JOIN R_PART RP
    ON P.ID_PATIENT = RP.SRC_ID
   AND RP.SRC_TYP = 'Patient';



INSERT INTO O_STFF
SELECT
    RP.PART_ID,
    P.TS_DEBUT_ACTIVITE,
    P.TS_FIN_ACTIVITE,
    TRIM(P.RAISON_FIN_ACTIVITE),
    $EXEC_ID


FROM WRK.PUBLIC.PERSONNEL P
INNER JOIN R_PART RP
    ON P.ID_PERSONNEL = RP.SRC_ID
   AND TRIM(P.FONCTION_PERSONNEL) = RP.SRC_TYP;

INSERT INTO O_CONS
SELECT
    C.ID_CONSULT,
    RP_STAFF.PART_ID       AS STFF_ID,
    RP_PATIENT.PART_ID     AS PATN_ID,
    C.TS_DEBUT_CONSULT,
    C.TS_FIN_CONSULT,
    C.POIDS_PATIENT,
    C.TEMP_PATIENT,
    TRIM(C.UNIT_TEMP),
    C.TENSION_PATIENT,
    TRIM(C.DSC_PATHO),
    CASE WHEN TRIM(C.INDIC_DIABETE) = 'True' THEN 1 ELSE 0 END,
    C.ID_TRAITEMENT,                                 
    CASE WHEN TRIM(C.INDIC_HOSPI) = 'True' THEN 1 ELSE 0 END,
    $EXEC_ID 
FROM WRK.PUBLIC.CONSULTATION C

LEFT JOIN R_PART RP_STAFF
    ON C.ID_PERSONNEL = RP_STAFF.SRC_ID
   AND RP_STAFF.SRC_TYP NOT IN ('Patient')

LEFT JOIN R_PART RP_PATIENT
    ON C.ID_PATIENT = RP_PATIENT.SRC_ID
   AND RP_PATIENT.SRC_TYP = 'Patient';

INSERT INTO O_HOSP
SELECT
    H.ID_HOSPI,
    H.ID_CONSULT,
    H.NO_CHAMBRE,
    H.TS_DEBUT_HOSPI,
    H.TS_FIN_HOSPI,
    H.COUT_HOSPI,
    RP_STAFF.PART_ID,
    $EXEC_ID
FROM WRK.PUBLIC.HOSPITALISATION H
LEFT JOIN R_PART RP_STAFF
    ON H.ID_PERSONNEL_RESP = RP_STAFF.SRC_ID
   AND RP_STAFF.SRC_TYP NOT IN ('Patient');