-- L'ordre est important pour eviter de supprimer des tables pointées par une FK
DROP TABLE IF EXISTS HOSPITALISATION;
DROP TABLE IF EXISTS CONSULTATION;
DROP TABLE IF EXISTS CHAMBRE;
DROP TABLE IF EXISTS PATIENT
DROP TABLE IF EXISTS PERSONNEL;
DROP TABLE IF EXISTS TRAITEMENT;
DROP TABLE IF EXISTS MEDICAMENT;


-- ---------------------------------------------------------
-- ---------------------- MEDICAMENT -----------------------
-- ---------------------------------------------------------
CREATE TABLE MEDICAMENT (
    CD_MEDICAMENT VARCHAR(10) NOT NULL,
    NOM_MEDICAMENT VARCHAR(250)
    CONDIT_MEDICAMENT VARCHAR(100),
    CATG_MEDICAMENT VARCHAR(100) NOT NULL,
    MARQUE_FABRI VARCHAR(100) NOT NULL,

    CONSTRAINT PK_MEDICAMENT PRIMARY KEY (CD_MEDICAMENT)
);

-- ---------------------------------------------------------
-- ---------------------- TRAITEMENT -----------------------
-- ---------------------------------------------------------
CREATE TABLE TRAITEMENT (
    ID_TRAITEMENT INTEGER NOT NULL,
    CD_MEDICAMENT VARCHAR(10) NOT NULL,
    ID_COSULTATION INTEGER NOT NULL,
    CATG_MEDICAMENT VARCHAR(100) NOT NULL,
    MARQUE_FABRI VARCHAR(100) NOT NULL,
    QTE_MEDICAMENT INTEGER,
    DSC_POSOLOGIE VARCHAR(100) NOT NULL,
    TS_CREATION_TRAITEMENT TIMESTAMP(0) NOT NULL,
)