@startuml schema_physique
title AI07 - Projet - Schéma physique de la base de données

note as N_Source
  Source des informations :
  * Hopital Mapping VF.xlsx
  
  Formalisme :
  * <u>Clé primaire</u>
  * <i>Clé étrangère</i>
end note

class CHAMBRE {
  {static} NO_CHAMBRE {key}: INTEGER
  NOM_CHAMBRE: VARCHAR[20]
  NO_ETAGE: BYTEINT
  NOM_BATIMENT: VARCHAR[20]
  TYPE_CHAMBRE: VARCHAR[10]
  PRIX_JOUR: SMALLINT
  DT_CREATION: DATE
}

class TRAITEMENT {
  {static} ID_TRAITEMENT {key}: INTEGER
  {abstract} CD_MEDICAMENT {fkey}: INTEGER
  CATG_MEDICAMENT: VARCHAR[100]
  MARQUE_FABRI: VARCHAR[100]
  QTE_MEDICAMENT: SMALLINT
  DSC_POSOLOGIE: VARCHAR[100]
  ID_CONSULT: INTEGER
  TS_CREATION_TRAITEMENT: TIMESTAMP[0]
}

class PERSONNEL {
  {static} ID_PERSONNEL {key}: INTEGER
  NOM_PERSONNEL: VARCHAR[100]
  PRENOM_PERSONNEL: VARCHAR[100]
  FONCTION_PERSONNEL: VARCHAR[50]
  TS_DEBUT_ACTIVITE: TIMESTAMP[0]
  TS_FIN_ACTIVITE: TIMESTAMP[0]
  RAISON_FIN_ACTIVITE: VARCHAR[100]
  TS_CREATION_PERSONNEL: TIMESTAMP[0]
  TS_MAJ_PERSONNEL: TIMESTAMP[0]
  CD_STATUT_PERSONNEL: VARCHAR[10]
}

class PATIENT {
  {static} ID_PATIENT {key}: INTEGER
  NOM_PATIENT: VARCHAR[100]
  PRENOM_PATIENT: VARCHAR[100]
  DT_NAISS: DATE
  VILLE_NAISS: VARCHAR[100]
  PAYS_NAISS: VARCHAR[100]
  NUM_SECU: VARCHAR[15]
  IND_PAYS_NUM_TELP: VARCHAR[5]
  NUM_TELEPHONE: VARCHAR[20]
  NUM_VOIE: VARCHAR[10]
  DSC_VOIE: VARCHAR[250]
  CMPL_VOIE: VARCHAR[250]
  CD_POSTAL: VARCHAR[10]
  VILLE: VARCHAR[100]
  PAYS: VARCHAR[100]
  TS_CREATION_PATIENT: TIMESTAMP[0]
  TS_MAJ_PATIENT: TIMESTAMP[0]
}

class CONSULTATION {
  {static} ID_CONSULT {key}: INTEGER
  {abstract} ID_PERSONNEL {fkey}: INTEGER
  {abstract} ID_PATIENT {fkey}: INTEGER
  TS_DEBUT_CONSULT: TIMESTAMP[0]
  TS_FIN_CONSULT: TIMESTAMP[0]
  POIDS_PATIENT: INTEGER
  TEMP_PATIENT: INTEGER
  UNIT_TEMP: VARCHAR[15]
  TENSION_PATIENT: INTEGER
  DSC_PATHO: VARCHAR[250]
  INDIC_DIABETE: VARCHAR[10] {boolean}
  ID_TRAITEMENT: INTEGER
  INDIC_HOSPI: VARCHAR[10] {boolean}
}

class HOSPITALISATION {
  {static} ID_HOSPI {key}: INTEGER
  {abstract} ID_CONSULT {fkey}: INTEGER
  {abstract} NO_CHAMBRE {fkey}: SMALLINT
  TS_DEBUT_HOSPI: TIMESTAMP[0]
  TS_FIN_HOSPI: TIMESTAMP[0]
  COUT_HOSPI: TIMESTAMP[0] [???]
  ID_PERSONNEL_RESP: INTEGER
}

class MEDICAMENT {
  {static} CD_MEDICAMENT {key}: VARCHAR[10] 
  NOM_MEDICAMENT: VARCHAR[250]
  CONDIT_MEDICAMENT: VARCHAR[100]
  CATG_MEDICAMENT: VARCHAR[100]
  MARQUE_FABRI: VARCHAR[100]
}

TRAITEMENT --> MEDICAMENT : CD_MEDICAMENT

CONSULTATION --> PERSONNEL : ID_PERSONNEL
CONSULTATION --> PATIENT : ID_PATIENT
CONSULTATION --> TRAITEMENT : ID_TRAITEMENT

HOSPITALISATION --> CONSULTATION : ID_CONSULT 
HOSPITALISATION --> CHAMBRE : NO_CHAMBRE
@enduml
